### ISSUE TITLE
Yang set packing is buggy

### ISSUE THREAD

**Issue by CharJon** [CharJon/mpgen#8]
While the set packing instances have similar structure to the set cover, they are not the same.

- [ ] set packing is maximization problem
- [ ] the constraints are of type <= 1 not >= 1

**Comment by mmghannam** [comment]
> While the set packing instances have similar structure to the set cover, they are not the same.
> 
> * [ ]  set packing is minimization problem
> * [ ]  the constraints are of type <= 1 not >= 1

you mean Maximization right? 😄
